kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: annette-frontend
spec:
  host: annette-console.domain.com
  to:
    kind: Service
    name: annette-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: annette-backend
spec:
  host: annette-console.domain.com
  path: /api
  to:
    kind: Service
    name: api-gateway
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: annette-camunda
spec:
  host: annette-camunda.domain.com
  to:
    kind: Service
    name: camunda
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

