version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.13.3
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:latest
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200

  cassandra:
    image: cassandra:3.11.12
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=AnnetteCluster

  minio:
    image: 'minio/minio:latest'
    ports:
      - '9002:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: 'server /data --console-address ":9001"'

  postgres:
    build: ./postgres/
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_DEFAULT_EMAIL: postgres@example.com

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 3080:8080
    depends_on:
      - postgres

  camunda:
    build: ./camunda/
    environment:
        - DB_DRIVER=org.postgresql.Driver
        - DB_URL=jdbc:postgresql://postgres:5432/camunda
        - DB_USERNAME=camunda
        - DB_PASSWORD=camunda
        - WAIT_FOR=postgres:5432
    links:
        - postgres
    ports:
        - "3090:8080"

volumes:
  odfe-data1:
  cassandra-data:
  minio-data:
  pg-data:
