camunda.bpm:
  admin-user:
    id: camunda
    password: camunda
# https://docs.camunda.org/manual/latest/user-guide/security/#http-header-security-in-webapps
# https://docs.camunda.org/manual/latest/webapps/shared-options/header-security/
  webapp:
    csrf:
      enable-same-site-cookie: true
      same-site-cookie-option: STRICT
    header-security:
      hsts-disabled: false
      content-security-policy-value: base-uri 'self';
        default-src 'self' 'unsafe-inline' 'unsafe-eval';
        img-src 'self' data:;
        block-all-mixed-content;
        form-action 'self';
        frame-ancestors 'none';
        object-src 'none';
        sandbox
          allow-forms
          allow-scripts
          allow-same-origin
          allow-popups

# https://docs.camunda.org/manual/latest/user-guide/security/#authorization
# https://docs.camunda.org/manual/latest/user-guide/process-engine/authorization-service/
  authorization.enabled: true

  run:
# https://docs.camunda.org/manual/latest/user-guide/security/#authentication
# https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#authentication
    auth.enabled: true

# https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#logging
# https://docs.camunda.org/manual/latest/user-guide/logging/#process-engine
logging:
   level.root: INFO
   file.name: logs/camunda-bpm-run.log

# By default, Spring Boot serves static content from any directories called /static or /public or /resources or
# /META-INF/resources in the classpath. To prevent users from accidentally sharing files, this is disabled here by setting static locations to NULL.
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content
spring.web.resources:
  static-locations: NULL